In [1]:
# use these links to do so:

# use these links to do so:
import numpy as np
import pandas as pd
import warnings
warnings.filterwarnings('ignore')


import matplotlib.pyplot as plt


import seaborn as sns
sns.set()
sns.set_style("white")


import plotly.offline as py
py.init_notebook_mode(connected=True)
import plotly.graph_objs as go
import plotly.tools as tls

from sklearn.tree import DecisionTreeClassifier

from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import (accuracy_score, log_loss, classification_report)
import xgboost

from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split, StratifiedKFold
from xgboost import XGBClassifier
from sklearn.metrics import roc_auc_score

Using TensorFlow backend.

In [2]:
df = pd.read_csv('Train_Set.csv')
df.head(87)

,account_id,week_start_date,feature1,feature2,feature3,feature4,feature5,feature6,feature7,feature8,...,feature54,feature55,feature56,feature57,feature58,feature59,feature60,feature61,feature62,Label
0,100559.0,2018-09-03,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
1,101026.0,2018-09-03,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
2,101026.0,2018-09-10,0.0,0.0,86.666667,0.0,0.0,0.0,0.0,0.0,...,0.0,0.333333,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
3,101026.0,2018-09-17,0.0,0.0,-0.076046,0.0,0.0,0.0,0.0,0.0,...,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
4,101026.0,2018-09-24,0.0,0.0,-0.987654,0.0,0.0,0.0,0.0,0.0,...,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
82,101026.0,2020-03-16,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
83,101026.0,2020-03-23,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
84,101026.0,2020-03-30,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
85,103037.0,2018-09-03,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
86,103037.0,2018-09-10,0.0,0.0,1.500000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0

In [3]:
df.tail()

,account_id,week_start_date,feature1,feature2,feature3,feature4,feature5,feature6,feature7,feature8,...,feature54,feature55,feature56,feature57,feature58,feature59,feature60,feature61,feature62,Label
114701,237574.0,2020-03-30,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
114702,238407.0,2020-03-23,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
114703,238407.0,2020-03-30,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
114704,102119.0,2020-03-30,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
114705,101817.0,2020-03-30,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0

In [4]:
df.isnull().any()
df['Label'].value_counts()

0    113630
1      1076
Name: Label, dtype: int64

In [5]:
df['account_id'].value_counts()

104959.0    280
105810.0    278
109056.0    278
100618.0    274
102171.0    272
           ...
100796.0      1
187594.0      1
101642.0      1
239954.0      1
239955.0      1
Name: account_id, Length: 2690, dtype: int64

In [6]:
from datetime import datetime
 
year = lambda x: datetime.strptime(x, "%Y-%m-%d" ).year
df['year'] = df['week_start_date'].map(year)
month = lambda x: datetime.strptime(x, "%Y-%m-%d" ).month
df['month'] = df['week_start_date'].map(month)
day = lambda x: datetime.strptime(x, "%Y-%m-%d" ).day
df['day'] = df['week_start_date'].map(day)

In [7]:
df1=df.copy()
df1['week_start_date']= pd.to_datetime(df['week_start_date'])
df1['days_sincelast_event'] = df1.groupby('account_id')['week_start_date'].diff().apply(lambda x: x.days)
df1['Week_Number'] = df1['week_start_date'].dt.week
# dropping ALL duplicte values 
df1.drop_duplicates(subset =["account_id","week_start_date" ],
                     keep = 'first', inplace = True) 

df1=df1.sort_values(by=['account_id', 'week_start_date'],ascending=True)
df1.head(25)

,account_id,week_start_date,feature1,feature2,feature3,feature4,feature5,feature6,feature7,feature8,...,feature59,feature60,feature61,feature62,Label,year,month,day,days_sincelast_event,Week_Number
74211,100000.0,2019-06-03,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0,2019,6,3,NaN,23
74212,100000.0,2019-06-10,0.533333,0.000000,27.133333,0.0,0.0,0.000000,1.400000,0.000000,...,0.066667,0.200000,0.000000,9.533333,0,2019,6,10,7.0,24
74213,100000.0,2019-06-17,0.043478,0.000000,0.289100,0.0,0.0,0.000000,0.250000,0.000000,...,0.187500,-0.055556,0.000000,0.259494,0,2019,6,17,7.0,25
74214,100000.0,2019-06-24,0.187500,0.000000,0.737132,0.0,0.0,0.100000,0.166667,0.200000,...,-0.052632,-0.117647,0.000000,0.854271,0,2019,6,24,7.0,26
74215,100000.0,2019-07-01,-0.135338,0.000000,-0.612245,0.0,0.0,-0.090909,-0.571429,-0.107143,...,-0.166667,0.000000,0.000000,-0.668990,0,2019,7,1,7.0,27
74216,100000.0,2019-07-08,0.014493,0.000000,0.930799,0.0,0.0,0.722222,1.074074,0.088889,...,0.222222,0.222222,0.000000,1.244639,0,2019,7,8,7.0,28
74217,100000.0,2019-07-15,0.114286,0.000000,-0.009591,0.0,0.0,-0.170507,-0.104592,0.285714,...,-0.064935,-0.123377,0.000000,0.031698,0,2019,7,15,7.0,29
74218,100000.0,2019-07-22,-0.115385,0.000000,0.310398,0.0,0.0,-0.300000,0.025641,-0.333333,...,-0.125000,-0.066667,0.000000,0.352273,0,2019,7,22,7.0,30
74219,100000.0,2019-07-29,-0.026087,0.000000,-0.436951,0.0,0.0,0.333333,-0.206667,0.200000,...,0.066667,0.066667,0.000000,-0.309804,0,2019,7,29,7.0,31
74220,100000.0,2019-08-05,-0.017857,0.000000,0.239293,0.0,0.0,-0.250000,0.165966,0.011905,...,0.875000,0.071429,0.000000,0.030844,0,2019,8,5,7.0,32
74221,100000.0,2019-08-12,0.000000,0.000000,-0.031773,0.0,0.0,0.000000,-0.135135,-0.176471,...,-0.428571,-0.062500,0.000000,-0.185039,0,2019,8,12,7.0,33
74222,100000.0,2019-08-19,0.060606,0.000000,-0.011860,0.0,0.0,0.066667,-0.183333,0.133333,...,-0.125000,-0.066667,0.000000,0.248953,0,2019,8,19,7.0,34
74223,100000.0,2019-08-26,0.145455,0.000000,0.074448,0.0,0.0,-0.062500,0.704545,0.283422,...,0.090909,0.000000,0.000000,0.161798,0,2019,8,26,7.0,35
74224,100000.0,2019-09-02,-0.095238,0.000000,-0.211180,0.0,0.0,0.000000,-0.371429,-0.187500,...,0.166667,0.090909,0.000000,-0.025424,0,2019,9,2,7.0,36
74225,100000.0,2019-09-09,0.113360,0.000000,-0.093882,0.0,0.0,0.000000,0.692308,-0.088757,...,-0.153846,0.057692,0.000000,0.191973,0,2019,9,9,7.0,37
74226,100000.0,2019-09-16,-0.003333,0.000000,0.093954,0.0,0.0,0.000000,0.009470,0.005952,...,-0.071429,-0.061111,0.000000,-0.277778,0,2019,9,16,7.0,38
74227,100000.0,2019-09-23,0.043478,0.000000,-0.007061,0.0,0.0,0.090909,0.090909,-0.076923,...,0.454545,-0.076923,0.000000,-0.060606,0,2019,9,23,7.0,39
74228,100000.0,2019-09-30,-0.038462,0.000000,-0.070359,0.0,0.0,-0.083333,-0.030019,0.000000,...,-0.206731,0.153846,0.000000,-0.035567,0,2019,9,30,7.0,40
74229,100000.0,2019-10-07,-0.071429,0.142857,-0.249480,0.0,0.0,0.000000,-0.268997,0.071429,...,-0.009524,-0.071429,0.357143,-0.470013,0,2019,10,7,7.0,41
74230,100000.0,2019-10-14,0.120000,-0.062500,0.189189,0.0,0.0,0.285714,0.081081,0.066667,...,-0.062500,0.133333,0.157895,-0.834711,0,2019,10,14,7.0,42
74231,100000.0,2019-10-21,0.090909,-0.066667,0.504132,0.0,0.0,-0.151515,-0.013636,0.034091,...,0.187879,-0.101604,-0.132231,1.290909,0,2019,10,21,7.0,43
74232,100000.0,2019-10-28,-0.228070,0.000000,-0.486617,0.0,0.0,-0.083333,-0.346350,-0.153846,...,-0.214286,-0.083333,-0.150877,-0.694444,0,2019,10,28,7.0,44
74233,100000.0,2019-11-04,0.102679,0.000000,0.582788,0.0,0.0,0.071429,0.667347,0.071429,...,0.071429,0.357143,-0.012987,0.000000,0,2019,11,4,7.0,45
74234,100000.0,2019-11-11,-0.047337,0.000000,-0.012079,0.0,0.0,0.292308,0.001789,0.005128,...,-0.066667,-0.263158,-0.125000,0.000000,0,2019,11,11,7.0,46
74235,100000.0,2019-11-18,-0.039130,0.000000,0.174099,0.0,0.0,-0.205556,0.137500,0.114286,...,0.000000,0.000000,0.000000,0.000000,0,2019,11,18,7.0,47

In [8]:
df.tail(20)

,account_id,week_start_date,feature1,feature2,feature3,feature4,feature5,feature6,feature7,feature8,...,feature57,feature58,feature59,feature60,feature61,feature62,Label,year,month,day
114686,101210.0,2020-03-30,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0,2020,3,30
114687,187622.0,2020-03-30,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0,2020,3,30
114688,233667.0,2020-03-30,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0,2020,3,30
114689,107606.0,2020-03-30,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0,2020,3,30
114690,100134.0,2020-03-23,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0,2020,3,23
114691,100134.0,2020-03-30,0.0,0.0,317.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0,2020,3,30
114692,187639.0,2020-03-30,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0,2020,3,30
114693,185334.0,2020-03-30,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0,2020,3,30
114694,188011.0,2020-03-30,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0,2020,3,30
114695,186052.0,2020-03-30,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0,2020,3,30
114696,128201.0,2020-03-30,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0,2020,3,30
114697,236556.0,2020-03-30,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0,2020,3,30
114698,181233.0,2020-03-30,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0,2020,3,30
114699,186843.0,2020-03-30,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0,2020,3,30
114700,187190.0,2020-03-30,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0,2020,3,30
114701,237574.0,2020-03-30,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0,2020,3,30
114702,238407.0,2020-03-23,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0,2020,3,23
114703,238407.0,2020-03-30,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0,2020,3,30
114704,102119.0,2020-03-30,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0,2020,3,30
114705,101817.0,2020-03-30,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0,2020,3,30

In [9]:
df1.tail()

,account_id,week_start_date,feature1,feature2,feature3,feature4,feature5,feature6,feature7,feature8,...,feature59,feature60,feature61,feature62,Label,year,month,day,days_sincelast_event,Week_Number
114660,239655.0,2020-03-30,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0,2020,3,30,NaN,14
114685,239689.0,2020-03-30,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0,2020,3,30,NaN,14
114654,239711.0,2020-03-30,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0,2020,3,30,NaN,14
114658,239954.0,2020-03-30,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0,2020,3,30,NaN,14
114661,239955.0,2020-03-30,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0,2020,3,30,NaN,14

In [10]:
df1.reset_index(inplace=True)

In [11]:
df1.tail(50)

,index,account_id,week_start_date,feature1,feature2,feature3,feature4,feature5,feature6,feature7,...,feature59,feature60,feature61,feature62,Label,year,month,day,days_sincelast_event,Week_Number
91245,113947,236213.0,2020-03-16,0.000000,0.0,3.000000,0.0,0.0,1.0,0.000000,...,0.0,0.0,0.0,0.0,0,2020,3,16,7.0,12
91246,113948,236213.0,2020-03-23,0.000000,0.0,-0.750000,0.0,0.0,-0.5,0.000000,...,0.0,0.0,0.0,0.0,0,2020,3,23,7.0,13
91247,113949,236213.0,2020-03-30,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,...,0.0,0.0,0.0,0.0,0,2020,3,30,7.0,14
91248,114697,236556.0,2020-03-30,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,...,0.0,0.0,0.0,0.0,0,2020,3,30,NaN,14
91249,113942,236574.0,2020-03-09,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,...,0.0,0.0,0.0,0.0,0,2020,3,9,NaN,11
91250,113943,236574.0,2020-03-16,0.000000,0.0,0.333333,0.0,0.0,0.0,0.000000,...,0.0,0.0,0.0,0.0,0,2020,3,16,7.0,12
91251,113944,236574.0,2020-03-23,0.000000,0.0,-0.250000,0.0,0.0,0.0,0.000000,...,0.0,0.0,0.0,0.0,0,2020,3,23,7.0,13
91252,113945,236574.0,2020-03-30,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,...,0.0,0.0,0.0,0.0,0,2020,3,30,7.0,14
91253,114104,236583.0,2020-03-09,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,...,0.0,0.0,0.0,0.0,0,2020,3,9,NaN,11
91254,114105,236583.0,2020-03-16,0.000000,0.0,9.000000,0.0,0.0,0.0,0.000000,...,0.0,0.0,0.0,0.0,0,2020,3,16,7.0,12
91255,114106,236583.0,2020-03-23,0.000000,0.0,0.150000,0.0,0.0,0.0,0.000000,...,0.0,0.0,0.0,0.0,0,2020,3,23,7.0,13
91256,114107,236583.0,2020-03-30,0.000000,0.0,2.652174,0.0,0.0,0.0,0.000000,...,0.0,0.0,0.0,0.0,0,2020,3,30,7.0,14
91257,114511,236767.0,2020-03-16,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,...,0.0,0.0,0.0,0.0,0,2020,3,16,NaN,12
91258,114512,236767.0,2020-03-23,0.857143,0.0,0.714286,0.0,0.0,0.0,0.285714,...,0.0,0.0,0.0,0.0,0,2020,3,23,7.0,13
91259,114513,236767.0,2020-03-30,0.076923,0.0,0.166667,0.0,0.0,0.0,0.555556,...,0.0,0.0,0.0,0.0,0,2020,3,30,7.0,14
91260,114096,236769.0,2020-03-09,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,...,0.0,0.0,0.0,0.0,0,2020,3,9,NaN,11
91261,114097,236769.0,2020-03-16,0.000000,0.0,8.250000,0.0,0.0,0.0,0.000000,...,0.0,0.0,0.0,0.0,0,2020,3,16,7.0,12
91262,114098,236769.0,2020-03-23,0.000000,0.0,0.081081,0.0,0.0,0.0,0.000000,...,0.0,0.0,0.0,0.0,0,2020,3,23,7.0,13
91263,114099,236769.0,2020-03-30,0.000000,0.0,2.600000,0.0,0.0,0.0,0.000000,...,0.0,0.0,0.0,0.0,0,2020,3,30,7.0,14
91264,114582,237032.0,2020-03-23,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,...,0.0,0.0,0.0,0.0,0,2020,3,23,NaN,13
91265,114583,237032.0,2020-03-30,0.000000,0.0,142.000000,0.0,0.0,0.0,0.000000,...,0.0,0.0,0.0,0.0,0,2020,3,30,7.0,14
91266,114427,237247.0,2020-03-16,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,...,0.0,0.0,0.0,0.0,0,2020,3,16,NaN,12
91267,114428,237247.0,2020-03-23,0.000000,0.0,9.333333,0.0,0.0,0.0,0.000000,...,0.0,0.0,0.0,0.0,0,2020,3,23,7.0,13
91268,114429,237247.0,2020-03-30,0.000000,0.0,7.516129,0.0,0.0,0.0,0.000000,...,0.0,0.0,0.0,0.0,0,2020,3,30,7.0,14
91269,114535,237493.0,2020-03-16,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,...,0.0,0.0,0.0,0.0,0,2020,3,16,NaN,12
91270,114536,237493.0,2020-03-23,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,...,0.0,0.0,0.0,0.0,0,2020,3,23,7.0,13
91271,114537,237493.0,2020-03-30,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,...,0.0,0.0,0.0,0.0,0,2020,3,30,7.0,14
91272,114494,237573.0,2020-03-16,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,...,0.0,0.0,0.0,0.0,0,2020,3,16,NaN,12
91273,114495,237573.0,2020-03-23,0.000000,0.0,7.000000,0.0,0.0,0.0,0.000000,...,0.0,0.0,0.0,0.0,0,2020,3,23,7.0,13
91274,114496,237573.0,2020-03-30,0.000000,0.0,-0.500000,0.0,0.0,0.0,0.000000,...,0.0,0.0,0.0,0.0,0,2020,3,30,7.0,14
91275,114701,237574.0,2020-03-30,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,...,0.0,0.0,0.0,0.0,0,2020,3,30,NaN,14
91276,114596,237691.0,2020-03-23,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,...,0.0,0.0,0.0,0.0,0,2020,3,23,NaN,13
91277,114597,237691.0,2020-03-30,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,...,0.0,0.0,0.0,0.0,0,2020,3,30,7.0,14
91278,114532,238290.0,2020-03-16,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,...,0.0,0.0,0.0,0.0,0,2020,3,16,NaN,12
91279,114533,238290.0,2020-03-23,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,...,0.0,0.0,0.0,0.0,0,2020,3,23,7.0,13
91280,114534,238290.0,2020-03-30,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,...,0.0,0.0,0.0,0.0,0,2020,3,30,7.0,14
91281,114702,238407.0,2020-03-23,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,...,0.0,0.0,0.0,0.0,0,2020,3,23,NaN,13
91282,114703,238407.0,2020-03-30,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,...,0.0,0.0,0.0,0.0,0,2020,3,30,7.0,14
91283,114605,239005.0,2020-03-23,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,...,0.0,0.0,0.0,0.0,0,2020,3,23,NaN,13
91284,114606,239005.0,2020-03-30,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,...,0.0,0.0,0.0,0.0,0,2020,3,30,7.0,14
91285,114588,239114.0,2020-03-23,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,...,0.0,0.0,0.0,0.0,0,2020,3,23,NaN,13
91286,114589,239114.0,2020-03-30,0.000000,0.0,54.000000,0.0,0.0,0.0,0.000000,...,0.0,0.0,0.0,0.0,0,2020,3,30,7.0,14
91287,114487,239115.0,2020-03-23,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,...,0.0,0.0,0.0,0.0,0,2020,3,23,NaN,13
91288,114488,239115.0,2020-03-30,0.000000,0.0,52.000000,0.0,0.0,0.0,0.000000,...,0.0,0.0,0.0,0.0,0,2020,3,30,7.0,14
91289,114653,239428.0,2020-03-30,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,...,0.0,0.0,0.0,0.0,0,2020,3,30,NaN,14
91290,114660,239655.0,2020-03-30,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,...,0.0,0.0,0.0,0.0,0,2020,3,30,NaN,14
91291,114685,239689.0,2020-03-30,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,...,0.0,0.0,0.0,0.0,0,2020,3,30,NaN,14
91292,114654,239711.0,2020-03-30,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,...,0.0,0.0,0.0,0.0,0,2020,3,30,NaN,14
91293,114658,239954.0,2020-03-30,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,...,0.0,0.0,0.0,0.0,0,2020,3,30,NaN,14
91294,114661,239955.0,2020-03-30,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,...,0.0,0.0,0.0,0.0,0,2020,3,30,NaN,14

In [12]:
def func(x,year):
    init=pd.to_datetime('2018-09-03')
    if(year==2018):
        return x.isocalendar()[1]-init.isocalendar()[1]
    elif(year==2019):
        z=x.isocalendar()[1]
        return z+16
    elif(year==2020):
        return x.isocalendar()[1]+68
    

df1['weeks'] = df1.apply(lambda row : func(row['week_start_date'], 
                     row['year']), axis = 1) 
#df1['weeks']=df1['week_start_date'].map(func)
df1['id'] = df1.index
df1.tail(24)

,index,account_id,week_start_date,feature1,feature2,feature3,feature4,feature5,feature6,feature7,...,feature61,feature62,Label,year,month,day,days_sincelast_event,Week_Number,weeks,id
91271,114537,237493.0,2020-03-30,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0,2020,3,30,7.0,14,82,91271
91272,114494,237573.0,2020-03-16,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0,2020,3,16,NaN,12,80,91272
91273,114495,237573.0,2020-03-23,0.0,0.0,7.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0,2020,3,23,7.0,13,81,91273
91274,114496,237573.0,2020-03-30,0.0,0.0,-0.5,0.0,0.0,0.0,0.0,...,0.0,0.0,0,2020,3,30,7.0,14,82,91274
91275,114701,237574.0,2020-03-30,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0,2020,3,30,NaN,14,82,91275
91276,114596,237691.0,2020-03-23,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0,2020,3,23,NaN,13,81,91276
91277,114597,237691.0,2020-03-30,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0,2020,3,30,7.0,14,82,91277
91278,114532,238290.0,2020-03-16,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0,2020,3,16,NaN,12,80,91278
91279,114533,238290.0,2020-03-23,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0,2020,3,23,7.0,13,81,91279
91280,114534,238290.0,2020-03-30,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0,2020,3,30,7.0,14,82,91280
91281,114702,238407.0,2020-03-23,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0,2020,3,23,NaN,13,81,91281
91282,114703,238407.0,2020-03-30,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0,2020,3,30,7.0,14,82,91282
91283,114605,239005.0,2020-03-23,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0,2020,3,23,NaN,13,81,91283
91284,114606,239005.0,2020-03-30,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0,2020,3,30,7.0,14,82,91284
91285,114588,239114.0,2020-03-23,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0,2020,3,23,NaN,13,81,91285
91286,114589,239114.0,2020-03-30,0.0,0.0,54.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0,2020,3,30,7.0,14,82,91286
91287,114487,239115.0,2020-03-23,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0,2020,3,23,NaN,13,81,91287
91288,114488,239115.0,2020-03-30,0.0,0.0,52.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0,2020,3,30,7.0,14,82,91288
91289,114653,239428.0,2020-03-30,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0,2020,3,30,NaN,14,82,91289
91290,114660,239655.0,2020-03-30,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0,2020,3,30,NaN,14,82,91290
91291,114685,239689.0,2020-03-30,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0,2020,3,30,NaN,14,82,91291
91292,114654,239711.0,2020-03-30,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0,2020,3,30,NaN,14,82,91292
91293,114658,239954.0,2020-03-30,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0,2020,3,30,NaN,14,82,91293
91294,114661,239955.0,2020-03-30,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0,2020,3,30,NaN,14,82,91294

In [13]:
df1['days_sincelast_event']=df1['days_sincelast_event'].fillna(-1)
def func2(w,z):
    if z !=-1:
        return df1.loc[w-1,'Label']
    else:
        
        return -1
    

df1['one_week_prior_label'] = df1.apply(lambda row : func2(row['id'],row['days_sincelast_event']), axis = 1) 
df1['hack_1']=df1['days_sincelast_event'].copy()

def func3(w,z):
    if z !=-1:
        return w
        
    else:
        df1.loc[w+1,'hack_1']=-1
        return w
    

df1['hack_for_gettng_2_week_prior_value']=df1.apply(lambda row : func3(row['id'],row['days_sincelast_event']), axis = 1) 


def func4(w,z):
    if z !=-1:
        if(w-2 <0):
            return -2
        return df1.loc[w-2,'Label']
    else:
        
        return -2
    

df1['two_week_prior_label'] = df1.apply(lambda row : func4(row['id'],row['hack_1']), axis = 1) 

df1.tail(24)

,index,account_id,week_start_date,feature1,feature2,feature3,feature4,feature5,feature6,feature7,...,month,day,days_sincelast_event,Week_Number,weeks,id,one_week_prior_label,hack_1,hack_for_gettng_2_week_prior_value,two_week_prior_label
91272,114494.0,237573.0,2020-03-16,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,3.0,16.0,-1.0,12.0,80.0,91272.0,-1.0,-1.0,91272.0,-2.0
91273,114495.0,237573.0,2020-03-23,0.0,0.0,7.0,0.0,0.0,0.0,0.0,...,3.0,23.0,7.0,13.0,81.0,91273.0,0.0,-1.0,91273.0,-2.0
91274,114496.0,237573.0,2020-03-30,0.0,0.0,-0.5,0.0,0.0,0.0,0.0,...,3.0,30.0,7.0,14.0,82.0,91274.0,0.0,7.0,91274.0,0.0
91275,114701.0,237574.0,2020-03-30,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,3.0,30.0,-1.0,14.0,82.0,91275.0,-1.0,-1.0,91275.0,-2.0
91276,114596.0,237691.0,2020-03-23,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,3.0,23.0,-1.0,13.0,81.0,91276.0,-1.0,-1.0,91276.0,-2.0
91277,114597.0,237691.0,2020-03-30,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,3.0,30.0,7.0,14.0,82.0,91277.0,0.0,-1.0,91277.0,-2.0
91278,114532.0,238290.0,2020-03-16,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,3.0,16.0,-1.0,12.0,80.0,91278.0,-1.0,-1.0,91278.0,-2.0
91279,114533.0,238290.0,2020-03-23,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,3.0,23.0,7.0,13.0,81.0,91279.0,0.0,-1.0,91279.0,-2.0
91280,114534.0,238290.0,2020-03-30,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,3.0,30.0,7.0,14.0,82.0,91280.0,0.0,7.0,91280.0,0.0
91281,114702.0,238407.0,2020-03-23,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,3.0,23.0,-1.0,13.0,81.0,91281.0,-1.0,-1.0,91281.0,-2.0
91282,114703.0,238407.0,2020-03-30,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,3.0,30.0,7.0,14.0,82.0,91282.0,0.0,-1.0,91282.0,-2.0
91283,114605.0,239005.0,2020-03-23,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,3.0,23.0,-1.0,13.0,81.0,91283.0,-1.0,-1.0,91283.0,-2.0
91284,114606.0,239005.0,2020-03-30,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,3.0,30.0,7.0,14.0,82.0,91284.0,0.0,-1.0,91284.0,-2.0
91285,114588.0,239114.0,2020-03-23,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,3.0,23.0,-1.0,13.0,81.0,91285.0,-1.0,-1.0,91285.0,-2.0
91286,114589.0,239114.0,2020-03-30,0.0,0.0,54.0,0.0,0.0,0.0,0.0,...,3.0,30.0,7.0,14.0,82.0,91286.0,0.0,-1.0,91286.0,-2.0
91287,114487.0,239115.0,2020-03-23,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,3.0,23.0,-1.0,13.0,81.0,91287.0,-1.0,-1.0,91287.0,-2.0
91288,114488.0,239115.0,2020-03-30,0.0,0.0,52.0,0.0,0.0,0.0,0.0,...,3.0,30.0,7.0,14.0,82.0,91288.0,0.0,-1.0,91288.0,-2.0
91289,114653.0,239428.0,2020-03-30,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,3.0,30.0,-1.0,14.0,82.0,91289.0,-1.0,-1.0,91289.0,-2.0
91290,114660.0,239655.0,2020-03-30,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,3.0,30.0,-1.0,14.0,82.0,91290.0,-1.0,-1.0,91290.0,-2.0
91291,114685.0,239689.0,2020-03-30,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,3.0,30.0,-1.0,14.0,82.0,91291.0,-1.0,-1.0,91291.0,-2.0
91292,114654.0,239711.0,2020-03-30,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,3.0,30.0,-1.0,14.0,82.0,91292.0,-1.0,-1.0,91292.0,-2.0
91293,114658.0,239954.0,2020-03-30,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,3.0,30.0,-1.0,14.0,82.0,91293.0,-1.0,-1.0,91293.0,-2.0
91294,114661.0,239955.0,2020-03-30,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,3.0,30.0,-1.0,14.0,82.0,91294.0,-1.0,-1.0,91294.0,-2.0
91295,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-1.0,NaN,-2.0

In [14]:
df1=df1.drop(['index', 'account_id', 'week_start_date','hack_1', 'hack_for_gettng_2_week_prior_value','id','days_sincelast_event'], axis=1)
#df1=df1.drop(['index', 'account_id', 'week_start_date','hack_1', 'hack_for_gettng_2_week_prior_value','id','days_sincelast_event','year','day','month'], axis=1)

In [15]:
df1.columns

Index(['feature1', 'feature2', 'feature3', 'feature4', 'feature5', 'feature6',
       'feature7', 'feature8', 'feature9', 'feature10', 'feature11',
       'feature12', 'feature13', 'feature14', 'feature15', 'feature16',
       'feature17', 'feature18', 'feature19', 'feature20', 'feature21',
       'feature22', 'feature23', 'feature24', 'feature25', 'feature26',
       'feature27', 'feature28', 'feature29', 'feature30', 'feature31',
       'feature32', 'feature33', 'feature34', 'feature35', 'feature36',
       'feature37', 'feature38', 'feature39', 'feature40', 'feature41',
       'feature42', 'feature43', 'feature44', 'feature45', 'feature46',
       'feature47', 'feature48', 'feature49', 'feature50', 'feature51',
       'feature52', 'feature53', 'feature54', 'feature55', 'feature56',
       'feature57', 'feature58', 'feature59', 'feature60', 'feature61',
       'feature62', 'Label', 'year', 'month', 'day', 'Week_Number', 'weeks',
       'one_week_prior_label', 'two_week_prior_label'],
      dtype='object')

In [16]:
df1.tail()

,feature1,feature2,feature3,feature4,feature5,feature6,feature7,feature8,feature9,feature10,...,feature61,feature62,Label,year,month,day,Week_Number,weeks,one_week_prior_label,two_week_prior_label
91291,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,2020.0,3.0,30.0,14.0,82.0,-1.0,-2.0
91292,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,2020.0,3.0,30.0,14.0,82.0,-1.0,-2.0
91293,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,2020.0,3.0,30.0,14.0,82.0,-1.0,-2.0
91294,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,2020.0,3.0,30.0,14.0,82.0,-1.0,-2.0
91295,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-2.0

In [17]:
df1.columns

Index(['feature1', 'feature2', 'feature3', 'feature4', 'feature5', 'feature6',
       'feature7', 'feature8', 'feature9', 'feature10', 'feature11',
       'feature12', 'feature13', 'feature14', 'feature15', 'feature16',
       'feature17', 'feature18', 'feature19', 'feature20', 'feature21',
       'feature22', 'feature23', 'feature24', 'feature25', 'feature26',
       'feature27', 'feature28', 'feature29', 'feature30', 'feature31',
       'feature32', 'feature33', 'feature34', 'feature35', 'feature36',
       'feature37', 'feature38', 'feature39', 'feature40', 'feature41',
       'feature42', 'feature43', 'feature44', 'feature45', 'feature46',
       'feature47', 'feature48', 'feature49', 'feature50', 'feature51',
       'feature52', 'feature53', 'feature54', 'feature55', 'feature56',
       'feature57', 'feature58', 'feature59', 'feature60', 'feature61',
       'feature62', 'Label', 'year', 'month', 'day', 'Week_Number', 'weeks',
       'one_week_prior_label', 'two_week_prior_label'],
      dtype='object')

In [18]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 91296 entries, 0 to 91295
Data columns (total 70 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   feature1              91295 non-null  float64
 1   feature2              91295 non-null  float64
 2   feature3              91295 non-null  float64
 3   feature4              91295 non-null  float64
 4   feature5              91295 non-null  float64
 5   feature6              91295 non-null  float64
 6   feature7              91295 non-null  float64
 7   feature8              91295 non-null  float64
 8   feature9              91295 non-null  float64
 9   feature10             91295 non-null  float64
 10  feature11             91295 non-null  float64
 11  feature12             91295 non-null  float64
 12  feature13             91295 non-null  float64
 13  feature14             91295 non-null  float64
 14  feature15             91295 non-null  float64
 15  feature16             91295 non-null  float64
 16  feature17             91295 non-null  float64
 17  feature18             91295 non-null  float64
 18  feature19             91295 non-null  float64
 19  feature20             91295 non-null  float64
 20  feature21             91295 non-null  float64
 21  feature22             91295 non-null  float64
 22  feature23             91295 non-null  float64
 23  feature24             91295 non-null  float64
 24  feature25             91295 non-null  float64
 25  feature26             91295 non-null  float64
 26  feature27             91295 non-null  float64
 27  feature28             91295 non-null  float64
 28  feature29             91295 non-null  float64
 29  feature30             91295 non-null  float64
 30  feature31             91295 non-null  float64
 31  feature32             91295 non-null  float64
 32  feature33             91295 non-null  float64
 33  feature34             91295 non-null  float64
 34  feature35             91295 non-null  float64
 35  feature36             91295 non-null  float64
 36  feature37             91295 non-null  float64
 37  feature38             91295 non-null  float64
 38  feature39             91295 non-null  float64
 39  feature40             91295 non-null  float64
 40  feature41             91295 non-null  float64
 41  feature42             91295 non-null  float64
 42  feature43             91295 non-null  float64
 43  feature44             91295 non-null  float64
 44  feature45             91295 non-null  float64
 45  feature46             91295 non-null  float64
 46  feature47             91295 non-null  float64
 47  feature48             91295 non-null  float64
 48  feature49             91295 non-null  float64
 49  feature50             91295 non-null  float64
 50  feature51             91295 non-null  float64
 51  feature52             91295 non-null  float64
 52  feature53             91295 non-null  float64
 53  feature54             91295 non-null  float64
 54  feature55             91295 non-null  float64
 55  feature56             91295 non-null  float64
 56  feature57             91295 non-null  float64
 57  feature58             91295 non-null  float64
 58  feature59             91295 non-null  float64
 59  feature60             91295 non-null  float64
 60  feature61             91295 non-null  float64
 61  feature62             91295 non-null  float64
 62  Label                 91295 non-null  float64
 63  year                  91295 non-null  float64
 64  month                 91295 non-null  float64
 65  day                   91295 non-null  float64
 66  Week_Number           91295 non-null  float64
 67  weeks                 91295 non-null  float64
 68  one_week_prior_label  91295 non-null  float64
 69  two_week_prior_label  91296 non-null  float64
dtypes: float64(70)
memory usage: 52.0 MB

In [19]:
df1.dropna(axis=0, how='any', thresh=None, subset=None, inplace=True)
df1.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 91295 entries, 0 to 91294
Data columns (total 70 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   feature1              91295 non-null  float64
 1   feature2              91295 non-null  float64
 2   feature3              91295 non-null  float64
 3   feature4              91295 non-null  float64
 4   feature5              91295 non-null  float64
 5   feature6              91295 non-null  float64
 6   feature7              91295 non-null  float64
 7   feature8              91295 non-null  float64
 8   feature9              91295 non-null  float64
 9   feature10             91295 non-null  float64
 10  feature11             91295 non-null  float64
 11  feature12             91295 non-null  float64
 12  feature13             91295 non-null  float64
 13  feature14             91295 non-null  float64
 14  feature15             91295 non-null  float64
 15  feature16             91295 non-null  float64
 16  feature17             91295 non-null  float64
 17  feature18             91295 non-null  float64
 18  feature19             91295 non-null  float64
 19  feature20             91295 non-null  float64
 20  feature21             91295 non-null  float64
 21  feature22             91295 non-null  float64
 22  feature23             91295 non-null  float64
 23  feature24             91295 non-null  float64
 24  feature25             91295 non-null  float64
 25  feature26             91295 non-null  float64
 26  feature27             91295 non-null  float64
 27  feature28             91295 non-null  float64
 28  feature29             91295 non-null  float64
 29  feature30             91295 non-null  float64
 30  feature31             91295 non-null  float64
 31  feature32             91295 non-null  float64
 32  feature33             91295 non-null  float64
 33  feature34             91295 non-null  float64
 34  feature35             91295 non-null  float64
 35  feature36             91295 non-null  float64
 36  feature37             91295 non-null  float64
 37  feature38             91295 non-null  float64
 38  feature39             91295 non-null  float64
 39  feature40             91295 non-null  float64
 40  feature41             91295 non-null  float64
 41  feature42             91295 non-null  float64
 42  feature43             91295 non-null  float64
 43  feature44             91295 non-null  float64
 44  feature45             91295 non-null  float64
 45  feature46             91295 non-null  float64
 46  feature47             91295 non-null  float64
 47  feature48             91295 non-null  float64
 48  feature49             91295 non-null  float64
 49  feature50             91295 non-null  float64
 50  feature51             91295 non-null  float64
 51  feature52             91295 non-null  float64
 52  feature53             91295 non-null  float64
 53  feature54             91295 non-null  float64
 54  feature55             91295 non-null  float64
 55  feature56             91295 non-null  float64
 56  feature57             91295 non-null  float64
 57  feature58             91295 non-null  float64
 58  feature59             91295 non-null  float64
 59  feature60             91295 non-null  float64
 60  feature61             91295 non-null  float64
 61  feature62             91295 non-null  float64
 62  Label                 91295 non-null  float64
 63  year                  91295 non-null  float64
 64  month                 91295 non-null  float64
 65  day                   91295 non-null  float64
 66  Week_Number           91295 non-null  float64
 67  weeks                 91295 non-null  float64
 68  one_week_prior_label  91295 non-null  float64
 69  two_week_prior_label  91295 non-null  float64
dtypes: float64(70)
memory usage: 49.5 MB

In [20]:
y_train=df1['Label']
df1=df1.drop(['Label'],axis=1)

In [21]:
X_train, X_holdout, y_train, y_holdout = train_test_split(df1, y_train, test_size=0.3, random_state=17)

In [22]:
tree = DecisionTreeClassifier(max_depth=5, random_state=17)

rfc = RandomForestClassifier(n_estimators=100, max_depth=6, random_state=17)

xgb_clf = XGBClassifier(random_state=17)




scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_holdout_scaled = scaler.transform(X_holdout)

In [23]:

rfc.fit(X_train_scaled, y_train)
logit_pipe.fit(X_train, y_train)
xgb_clf.fit(X_train, y_train)

XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, gamma=0,
              learning_rate=0.1, max_delta_step=0, max_depth=3,
              min_child_weight=1, missing=None, n_estimators=100, n_jobs=1,
              nthread=None, objective='binary:logistic', random_state=17,
              reg_alpha=0, reg_lambda=1, scale_pos_weight=1, seed=None,
              silent=None, subsample=1, verbosity=1)

In [24]:
tree.fit(X_train, y_train)
rfc.fit(X_train_scaled, y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                       max_depth=6, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=17, verbose=0,
                       warm_start=False)

In [25]:
logit_val_pred = logit_pipe.predict(X_holdout)
tree_pred = tree.predict(X_holdout)

xgb_pred=xgb_clf.predict(X_holdout)

In [26]:
print('Training Set Accuracy of Logistic Regression Model:',logit_pipe.score(X_train, y_train))
print('Training Set Accuracy of our Decision Tree Model:',tree.score(X_train, y_train))
print('Training Set Accuracy of XgBoost Model:',xgb_clf.score(X_train, y_train))
print('Training Set Accuracy of Random Forest Model:',rfc.score(X_train_scaled, y_train))

Training Set Accuracy of Logistic Regression Model: 0.9953994930053516
Training Set Accuracy of our Decision Tree Model: 0.9965887397114512
Training Set Accuracy of XgBoost Model: 0.9965887397114512
Training Set Accuracy of Random Forest Model: 0.9956811566989016

In [27]:
from sklearn.metrics import accuracy_score
print('Accuracy of Logistic Regression Model:',accuracy_score(y_holdout, logit_val_pred))
print('Accuracy of our Decision Tree Model:',accuracy_score(y_holdout, tree_pred))# 0.94
print('Accuracy of XgBoost Model:',accuracy_score(y_holdout,xgb_pred))

Accuracy of Logistic Regression Model: 0.9950710139106941
Accuracy of our Decision Tree Model: 0.9960933221366242
Accuracy of XgBoost Model: 0.9961298331446932

In [28]:
tree_list = rfc.estimators_
#tree_list
print(rfc.feature_importances_)

[5.45134107e-04 0.00000000e+00 7.23702116e-03 1.76594046e-03
 0.00000000e+00 1.88736829e-04 4.32134680e-04 2.23788424e-04
 1.11162891e-03 1.77854217e-03 2.43441813e-02 5.13054131e-03
 0.00000000e+00 2.03470029e-04 3.38757408e-01 5.78762517e-02
 2.56460910e-03 5.49586479e-03 5.82651025e-03 3.91414904e-06
 2.46526466e-03 1.27024146e-02 1.78973834e-03 2.77197610e-04
 4.98371099e-05 1.29330389e-04 1.38413232e-04 1.33002028e-03
 0.00000000e+00 0.00000000e+00 2.20382906e-03 1.29131876e-03
 4.61973268e-04 1.32797099e-03 1.05955762e-04 1.45763084e-03
 7.44731708e-02 3.49590693e-03 4.07009285e-04 2.50895875e-03
 3.02783297e-03 2.08717488e-04 1.01972779e-02 5.95667175e-04
 2.25467770e-05 4.82440815e-04 5.47818054e-03 2.67879213e-04
 3.15783829e-06 2.40783343e-04 1.44781192e-06 0.00000000e+00
 9.70962988e-03 1.60644697e-03 8.56655234e-03 5.76108744e-04
 8.84930853e-05 3.05038834e-04 1.81496864e-04 1.24373396e-03
 0.00000000e+00 6.22571826e-04 3.19847769e-03 7.37699862e-03
 6.18166829e-03 9.84168992e-03 1.96422450e-02 2.69365166e-01
 8.08661316e-02]

In [35]:
import pickle
f=open('xgboost.pkl','wb')
pickle.dump(xgb_clf,f,protocol=2)
f.close()
f=open('tree.pkl','wb')
pickle.dump(tree,f,protocol=2)
f.close()

In [34]:
xgb_clf

XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, gamma=0,
              learning_rate=0.1, max_delta_step=0, max_depth=3,
              min_child_weight=1, missing=None, n_estimators=100, n_jobs=1,
              nthread=None, objective='binary:logistic', random_state=17,
              reg_alpha=0, reg_lambda=1, scale_pos_weight=1, seed=None,
              silent=None, subsample=1, verbosity=1)

In [30]:
pd.DataFrame(rfc.feature_importances_,
             index=df1.columns, columns=['Importance']).sort_values(
    by='Importance', ascending=False)

                      Importance
feature15               0.338757
one_week_prior_label    0.269365
two_week_prior_label    0.080866
feature37               0.074473
feature16               0.057876
...                          ...
feature61               0.000000
feature13               0.000000
feature30               0.000000
feature2                0.000000
feature5                0.000000

[69 rows x 1 columns]